[package]
name = "tournament"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["sort", "tournament", "tree", "kway", "merge"]

[dependencies]
streaming-iterator = "0.1"

[dev-dependencies]
rand = "0.8"